version: '3.3'

services:
  laravel-9:
    image: drajathasan/laravel-9
    container_name: "laravel-9"
    restart: always
    ports:
      - 8800:80
    volumes:
      - ./httpd.conf:/etc/apache2/httpd.conf
      - ./laravel:/var/www/localhost/htdocs/
